"""Add diagram fields to Question model

Revision ID: 241992932408
Revises: a2f293200969
Create Date: 2026-10-10 07:49:44.532772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '241992932408'
down_revision: Union[str, Sequence[str], None] = 'a2f293200969'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('diagram_url', sa.String(length=1024), nullable=True))
    op.add_column('questions', sa.Column('diagram_alt_text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'diagram_alt_text')
    op.drop_column('questions', 'diagram_url')
    # ### end Alembic commands ###
