"""Add required question fields

Revision ID: 68a92dbb4501
Revises: 55e66ef2cb54
Create Date: 2026-10-10 00:05:27.924731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68a92dbb4501'
down_revision: Union[str, Sequence[str], None] = '55e66ef2cb54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('subskill', sa.String(length=255), nullable=True))
    op.add_column('questions', sa.Column('validation_status', sa.String(length=50), nullable=False))
    op.add_column('questions', sa.Column('publication_status', sa.String(length=50), nullable=False))
    op.add_column('questions', sa.Column('accepted_answer_spec', sa.JSON(), nullable=True))
    op.add_column('questions', sa.Column('misconception_tags', sa.JSON(), nullable=True))
    op.add_column('questions', sa.Column('solution_path', sa.JSON(), nullable=True))
    op.add_column('questions', sa.Column('socratic_prompt_metadata', sa.JSON(), nullable=True))
    op.add_column('questions', sa.Column('diagram_requirement_flag', sa.Boolean(), nullable=False))
    op.add_column('questions', sa.Column('version_number', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'version_number')
    op.drop_column('questions', 'diagram_requirement_flag')
    op.drop_column('questions', 'socratic_prompt_metadata')
    op.drop_column('questions', 'solution_path')
    op.drop_column('questions', 'misconception_tags')
    op.drop_column('questions', 'accepted_answer_spec')
    op.drop_column('questions', 'publication_status')
    op.drop_column('questions', 'validation_status')
    op.drop_column('questions', 'subskill')
    # ### end Alembic commands ###
