"""Add telemetry fields to Turn model

Revision ID: a2f293200969
Revises: 5446fa8c63d2
Create Date: 2026-10-10 07:48:30.834041

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a2f293200969'
down_revision: str | Sequence[str] | None = '5446fa8c63d2'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('turns', sa.Column('model_metadata', sa.JSON(), nullable=True))
    op.add_column('turns', sa.Column('langfuse_trace_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('turns', 'langfuse_trace_id')
    op.drop_column('turns', 'model_metadata')
    # ### end Alembic commands ###
